spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@orcl.chkv5c8s1oal.us-east-1.rds.amazonaws.com:1521:orcl
    username: HydraTrainee
    password: momonga
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
  aop:
    auto: true
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate: INFO